server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/subscription-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq_user
    password: rabbitmq_1234

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.json

logging:
  level:
    root: INFO
    org.springframework: DEBUG

scheduler:
  pool:
    size: 10
